# Generated by Django 4.2.6 on 2023-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
