# Generated by Django 4.2.7 on 2023-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
